import type { Metadata } from "next";
import "./globals.css";
import { pretendard } from "./lib/localfont";
import { ThemeProvider } from "next-themes";
import InternalLinkTooltip from "./component/internallink-tooltip";
import fs from 'fs';
import path from 'path';
import SideNav from "./component/side-nav";
import { Alert } from "./component/alert";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tags = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'public/all-tags.json'), 'utf8'));
  const keywordsTag = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'public/top-keywords-tag.json'), 'utf8'));

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${pretendard.className} antialiased font-normal md:overflow-hidden`}
      >
        <ThemeProvider disableTransitionOnChange>
          <div className="flex flex-col md:flex-row h-screen w-full p-8 gap-4">
            <SideNav tags={tags} kwByTag={keywordsTag} />
            <main className="relative left-0 top-0 md:absolute md:left-[22rem] flex flex-col h-full w-full md:w-[calc(100vw-22rem)] flex-1 items-center overflow-hidden">
              {children}
            </main>
          </div>

          <InternalLinkTooltip />

          <Alert />
        </ThemeProvider>
      </body>
    </html>
  );
}