import type { Metadata } from "next";
import "./globals.css";
import GlobalNav from "./component/global-nav";
import { pretendard } from "./lib/localfont";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} antialiased font-normal`}
      >
        <div className="flex h-screen w-screen p-8 gap-4">
          <GlobalNav />
          <main className="bg-gray-200 h-full w-full flex flex-col items-center">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}